package com.pengadaan.barang;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.awt.event.KeyEvent;

public class login extends javax.swing.JFrame {

    private PengadaanBarang aplikasiInventory = new PengadaanBarang();
    public start Start = new start();
    
    private String Jabatan;
    private JLabel lblNIK = new JLabel(), Label1 = new JLabel();
    
    public login() {
        initComponents();
        aplikasiInventory.konekkeDatabase();
    }

    public void verifikasi() {
        try{
            Statement st = aplikasiInventory.config.getConnection().createStatement();
            ResultSet rs = st.executeQuery("select * from karyawan where NIK = '"+
                    jTxtFldNIK.getText()+"' and pass = '"+jTxtFldPass.getText()+"' and pass != ''");
            
        if(rs.next()) {
                aplikasiInventory.saveNIK(jTxtFldNIK.getText());           
                aplikasiInventory.vsNIK = jTxtFldNIK.getText();    
                aplikasiInventory.Start.setVisible(true);
                aplikasiInventory.HakAkses();
                this.setVisible(false);
                
          }
        else{ JOptionPane.showMessageDialog(this,"Maaf, Anda tidak berhasil login dan mengakses aplikasi ini.");
              jTxtFldNIK.setText("");
              jTxtFldPass.setText("");
              jTxtFldNIK.requestFocus();
        }
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,"<html><tr>Maaf, Anda belum terhubung dengan database!</tr><tr>Jalankan kembali aplikasi ini setelah Anda terhubung dengan database.</tr></html>", "Perhatian",
                            JOptionPane.OK_OPTION);
        }
     }
    
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlblNIK = new javax.swing.JLabel();
        jlblpass = new javax.swing.JLabel();
        jlblxNIK = new javax.swing.JLabel();
        jlblxpass = new javax.swing.JLabel();
        jTxtFldNIK = new javax.swing.JTextField();
        jBtnlogin = new javax.swing.JButton();
        jTxtFldPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Sistem Pengadaan Barang");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 22, 184));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login1.png"))); // NOI18N
        jLabel1.setText("Login User");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 49, 49));
        jLabel2.setText("Created By sfandrianah");

        jlblNIK.setText("NIK");

        jlblpass.setText("Password");

        jlblxNIK.setText(":");

        jlblxpass.setText(":");

        jTxtFldNIK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtFldNIKKeyTyped(evt);
            }
        });

        jBtnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/green.png"))); // NOI18N
        jBtnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnloginActionPerformed(evt);
            }
        });

        jTxtFldPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtFldPassKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblNIK)
                    .addComponent(jlblpass))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblxNIK, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblxpass, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtFldNIK, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(jBtnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNIK)
                    .addComponent(jlblxNIK)
                    .addComponent(jTxtFldNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlblpass)
                        .addComponent(jlblxpass))
                    .addComponent(jTxtFldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnloginActionPerformed
        // TODO add your handling code here:
        verifikasi();
    }//GEN-LAST:event_jBtnloginActionPerformed

    private void jTxtFldPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFldPassKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jBtnlogin.doClick();
           }
    }//GEN-LAST:event_jTxtFldPassKeyTyped

    private void jTxtFldNIKKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFldNIKKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
                jTxtFldPass.requestFocus();
            }
    }//GEN-LAST:event_jTxtFldNIKKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTxtFldNIK;
    private javax.swing.JPasswordField jTxtFldPass;
    private javax.swing.JLabel jlblNIK;
    private javax.swing.JLabel jlblpass;
    private javax.swing.JLabel jlblxNIK;
    private javax.swing.JLabel jlblxpass;
    // End of variables declaration//GEN-END:variables
}
